# Generated by Django 6.0.6 on 2026-06-17 03:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activo',
            name='tipo',
            field=models.CharField(choices=[('HW', 'Hardware'), ('SW', 'Software'), ('INF', 'Información'), ('SER', 'Servicio'), ('PER', 'Personal')], max_length=10),
        ),
        migrations.AlterField(
            model_name='activo',
            name='confidencialidad',
            field=models.IntegerField(choices=[(1, 'Muy Bajo'), (2, 'Bajo'), (3, 'Medio'), (4, 'Alto'), (5, 'Muy Alto')]),
        ),
        migrations.AlterField(
            model_name='activo',
            name='disponibilidad',
            field=models.IntegerField(choices=[(1, 'Muy Bajo'), (2, 'Bajo'), (3, 'Medio'), (4, 'Alto'), (5, 'Muy Alto')]),
        ),
        migrations.AlterField(
            model_name='activo',
            name='integridad',
            field=models.IntegerField(choices=[(1, 'Muy Bajo'), (2, 'Bajo'), (3, 'Medio'), (4, 'Alto'), (5, 'Muy Alto')]),
        ),
        migrations.DeleteModel(
            name='TipoActivo',
        ),
    ]
